### ISSUE TITLE
TA Review (MIS/MG):

### ISSUE THREAD

**Issue by MatthewCollard** [SammyG7/Mac-AR#171]
@samm82

**Summary**

- [x] It could be presented more clearly (e.g., in a table); you're essentially repeating the information of which modules are being completed within each "subcategory" of dates.
- [x] AC3 should be more specific; which libraries would be updated? The Game Room Module is an Abstract Data Type (since there will be more than one game room, and it exists within the context of your program). I think the descriptions of the puzzle modules' secrets could be made more explicit (e.g., what does a "Math Puzzle Module" entail?). Libraries are modules without state information (e.g., just a list of functions).
- [x] Template content (like Dr. Smith's comments) should be removed. I think this also applies to "Software Eng means the module will be implemented by the Software Eng software." since this doesn't really make sense based on the rest of your document. Non-leaf modules (e.g., the Behaviour-Hiding Module), should have a dash indicating that they aren't leaf modules and therefore won't be implemented (as described in the second paragraph of the Module Decomposition). Minor grammar issues.
- [x] How does an array differ from the already-specified sequence? Some function names are capitalized while others don't; this should be made consistent (and should ideally match the convention of whatever language this will be implemented in). The names of OnUserLoggedIn and related functions are unintuitive; are they names you picked or from Vivox/Unity? Abstract data types should have constructors defined (and have the type of the created object listed as an "Exported Type").
- [x] Minor grammar issues/typos; "RefreshPlayerList" is called "RefreshList" when defining its semantics. In math mode, LaTeX treats letters as variables so their spacing gets messed up; make sure to format words so that they display correctly (try \text{}).
- [x] It looks like these puzzles are inspired by Keep Talking and Nobody Explodes; if this is the case, you should probably explicitly say so (both to avoid plagiarism accusations and to help potential future developers understand them).
- [x] No semantics for Initialize of Game Room Module. Functions should be in the same order when defining their syntax and semantics. There is a lot of information not defined; for example: Game Room Module: isJoining, GameScene, behaviour of unsuccessful JoinAsync, Lobby Voice Communication Module: Permission 
- [x] The "Local Variables" of the Text Communication and Simon Says Modules should be state variables, as should _vvm in the Voice Communication Module and success and code in the Code Puzzle Module. buttonsArray and colourDictionary aren't used. You shouldn't need to compare something to "1", "0", "True", or "False" to see if it's True or False. It doesn't really make sense for isMicPermissionGranted to have a transition if it is just outputted and doesn't actually change a state variable. What do the puzzle state Booleans represent? It doesn't look like the game modules define a logic for defining if a puzzle is completed or not. SymbolsArray should be defined more generally as a sequence of symbols (Strings?); you could specify the length of this array if that is relevant. An example for the Math Puzzle Module would make it more clear. The definition of CheckEntry seems pretty repetitive. You may be able to make some puzzle functions (e.g., ColourBlink) more generic (i.e., move them up to the Multiplayer Puzzle Level).
- [x] Are skip limits associated with players or groups? Can one player skip a puzzle for everyone? 
- [x] Is an Error Manager Module really necessary if, as far as I can tell, there is only one exception thrown by your modules? (This also may be incorrect; there is usually many reasons for an exception being thrown.)
- [x] I think that many of these modules have enough information to get the general sense of how to implement them, but there are many ambiguities/omissions. Some designs of what puzzle modules could look like would make them more clear.

**Deadline**

March 20th, 2024

**Estimated Work Hours**

6 hours

**Comment by ethanlucask** [comment]
Updated MG to fix several TA issues in MG. Only thing remaining for MG is fixing secret's for puzzles.

**Comment by SammyG7** [comment]
MIS:
- Updated constants, variables, and functions to have consistent syntax
- Added note where there are unintuitive names that we are not able to change
- Added constructors to modules with multiple instances
- Fixed all typos and syntax errors that we came across
- Puzzles are significantly far enough away from any existing games that no credit is warranted. Will try to make this clear in the commit message
- Removed Initialize from Game Room Module (couldn't find equivalent in code)
- Reordered functions to have same order in Exported Access Programs and Access Routine Semantics
- Defined previously undefined terms/ variables
- Text communication local variables, Simon Says local variables, and _vvm moved to state variables
- Removed state transition in IsMicPermissionGranted
- Attempted to make puzzle completion aspect more clear with the active variable and puzzle/ batch completed functions, actual isComplete boolean shouldn't be necessary 
- SymbolsArray removed
- Updated CheckEntry semantics to be more clear 
- Left functions such as ColourBlink as is since having them be more generic wouldn't benefit any of the puzzles, they are specific to the puzzle they were created for 
- Removed skip limits
- Added note that even though the number of errors handled by the error module is few, it is still critical for a real time system such as this
- Most ambiguity has been cleared up now that we have implementation to compare against

**Comment by SammyG7** [comment]
Partially implemented in #310

**Comment by ethanlucask** [comment]
We good on MG. Commit ID: 36ea37beb9efc9e0ecad57b8bc10418d2c66c6f4
