### ISSUE TITLE
Team 18 HA Review: PR1 is irrelevant to the recommended actions

### ISSUE THREAD

**Issue by jiaoa3** [SammyG7/Mac-AR#41]
If the system cannot handle too many users’ requests, having a Performance Requirement, PR1, stated as “The system shall respond to user interaction instantaneously as perceived by the user”, cannot limit the number of users.

![s1](https://github.com/SammyG7/Mac-AR/assets/77683292/67723d07-a664-47ae-b191-bc9dda2806f7)

![s2](https://github.com/SammyG7/Mac-AR/assets/77683292/8fbb450f-7ba9-4627-b482-f10c5ea36b64)

@CSchank

**Comment by ethanlucask** [comment]
The performance requirement (PR1) and the limiting of the number of users (H3-1) are not mutually exclusive. If there is a server issue caused by too many user's sending or receiving data from the server, then limiting the number of users is a valid mitigation strategy so that this performance requirement can be met. Therefore, this is not an issue.
